### ISSUE TITLE
Game exits on touchscreen press - Retroid Pocket Mini

### ISSUE THREAD

**Issue by hilly1** [JeodC/PortMaster-HoloCure#2]
Pressing anywhere on the touchscreen causes the game to instantly close. This happens at any point in the game, intro, menus, etc.

RP Mini with Rocknix beta: ROCKNIX-SD865.aarch64-20241023.img.gz

**Comment by JeodC** [comment]
> Pressing anywhere on the touchscreen causes the game to instantly close. This happens at any point in the game, intro, menus, etc.
> 
> 
> 
> RP Mini with Rocknix beta: ROCKNIX-SD865.aarch64-20241023.img.gz

Can you share your log.txt?

**Comment by hilly1** [comment]
[log.txt](https://github.com/user-attachments/files/17535082/log.txt)

**Comment by JeodC** [comment]
```
gml_Script___input_error (line -1)gml_Script_input_source_setgml_Script___input_hotswap_tickgml_Script___input_system_tickgml_Object_input_controller_object_Step_1ERROR in
action number 1
of  Step Event1
for object input_controller_object:


Input 6.0.1 Beta:
Cannot claim touch, no virtual button bindings have been created in a default profile (see __input_config_verbs_and_bindings())
 
at gml_Script___input_error
```

This game was not designed to have an android port, and it seems that in order to keep things that way, touch input will crash the game. I suggest simply not using the touchscreen. Perhaps rocknix will allow disabling it in the future.

**Comment by hilly1** [comment]
Gotcha. Thanks for taking a look at it.

**Comment by hilly1** [comment]
I came up with a solution, disable the touchscreen module then re-enable after the game exits. Not sure if this is the best way but it works.

`# Disable touchscreen
modprobe -r edt_ft5x06

# Run the game
$GPTOKEYB "gmloadernext" -c "./holocure.gptk" &
pm_platform_helper "$GAMEDIR/gmloadernext"
./gmloadernext game.apk

# Re-enable touchscreen
modprobe edt_ft5x06

# Kill processes
pm_finish
`

**Comment by JeodC** [comment]
I...had no idea that was a thing. Neat.

**Comment by hilly1** [comment]
It took a bit of searching and trial and error - I tried using xinput to disable it first but I think that only works for wayland or x.org. Listing the modules with lsmod gave me a lot of stuff that I couldn't recognize as a touchscreen, so I plopped the output into chatgpt and asked it which module related to a touchscreen - a quick google search confirmed it was right and I tested disabling and re-enabling it while Balatro was running as that has touch input. Thanks for the HoloCure port - really pleased with how it's running on the RP Mini.

**Comment by JeodC** [comment]
> It took a bit of searching and trial and error - I tried using xinput to disable it first but I think that only works for wayland or x.org. Listing the modules with lsmod gave me a lot of stuff that I couldn't recognize as a touchscreen, so I plopped the output into chatgpt and asked it which module related to a touchscreen - a quick google search confirmed it was right and I tested disabling and re-enabling it while Balatro was running as that has touch input. Thanks for the HoloCure port - really pleased with how it's running on the RP Mini.

Thanks for figuring it out! I added it to a commit.

**Comment by hilly1** [comment]
Sorry to re-open this - I'm not sure of the correct etiquette. The above method for disabling the RP Mini touchscreen no longer works in recent Rocknix versions as the touchscreen module appears to now be built-in to the kernel. unbinding and rebinding the device to the driver seems to work instead. the following lines can be used

`#disable touchscreen
echo 13-0038 > /sys/bus/i2c/drivers/edt_ft5x06/unbind`

...

`#re-enable touchscreen
echo 13-0038 > /sys/bus/i2c/drivers/edt_ft5x06/bind`
